Performance
ybadr99/vet-clinic-database pull request #6
Opened 2023-07-18 12:46 UTC by ybadr99

prepare db to enhance the performance 
add indexing 
![Screenshot from 2023-07-18 15-17-09](https://github.com/ybadr99/vet-clinic-database/assets/61107698/b7ff9607-0880-406e-9b21-5908ee822253)
![Screenshot from 2023-07-18 15-18-01](https://github.com/ybadr99/vet-clinic-database/assets/61107698/e7ebe30d-3488-4b8f-9792-8caedf67bf86)
![Screenshot from 2023-07-18 15-18-19](https://github.com/ybadr99/vet-clinic-database/assets/61107698/b29f7081-5d69-428a-955c-df7c96c89366)
![Screenshot from 2023-07-18 15-31-36](https://github.com/ybadr99/vet-clinic-database/assets/61107698/bbbf5a89-05fd-447c-9d04-bb27c868eea9)
![Screenshot from 2023-07-18 15-31-48](https://github.com/ybadr99/vet-clinic-database/assets/61107698/d2f4bb06-859e-446f-9fef-4835f4dadfd2)
![Screenshot from 2023-07-18 15-32-12](https://github.com/ybadr99/vet-clinic-database/assets/61107698/ded2e2f6-8a5b-40a0-abef-9174fb09ade7)

2023-07-18 13:13 UTC, Gambit142 requested changes
Hi @ybadr99 @WilhelmK109 👋, 

Good job so far!

## Highlights
- Populated database with data ✔️ 
- Created index on required columns ✔️ 
- Use of the `explain analyze` command ✔️ 

You still need to work on some issues to go to the next project, but you are almost there!

## Required Changes ♻️
_Kindly check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you consider them as they can improve your code._

You can also consider the following:

N/A

Cheers, and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

#### Please tag me in your question so I can receive the notification. You can tag me by typing @Gambit142

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think the code review was unfair, request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
```

2023-07-18 13:13 UTC, Gambit142 commented on data.sql
> +insert into owners (full_name, email) select 'Owner ' || generate_series(1,2500000), 'owner_' || generate_series(1,2500000) || '@mail.com';
- [ ] Great work inserting data the way it was recommended. However, I noticed in your screenshots that the execution time before improving performance is significantly lower than **_1 second (1000ms)_**. I would advise you to run this query two or three more times, make the `explain analyze` statement and take screenshots of the execution time that are equal to or more than _**1 second (1000ms)**_. 👍 😎 

#### You can check points _**3 and 4**_ of this [project requirement](https://github.com/microverseinc/curriculum-databases/blob/main/db-structure/vet_clinic_performance_audit.md) 💻

### Hint: 
- Ensure the queries highlighted below are run before the indexing using the `explain analyze` command: 

  - SELECT COUNT(*) FROM visits where animal_id = 4;

  - SELECT * FROM visits where vet_id = 2;

  - SELECT * FROM owners where email = 'owner_18327@mail.com';

- Then ensure that the execution time for each query is equal to or above **_1 second (1000ms)_** 
- Then take a screenshot and replace the old ones with the new screenshots. 
- Then you apply the indexing and run the `explain analyze` command, take the screenshot and attach the screenshots. 👍 💻

2023-07-18 16:15 UTC, Shedrack-Sunday requested changes
Hello @ybadr99        👋 

# CHANGES REQUIRED ♻️

Great work on the project 👏
You've done extremely well so far in this project,  However, there are some adjustments you need to make to move to the next project. 💯

![](https://user-images.githubusercontent.com/80612925/157397398-00904e26-60ec-46cd-9510-240661c250ef.gif)

## Highlights   
- Good use of GitHub features ✔️   
- Nice work with the SQL queries✔️ 
  
  
# Required Changes  🌵  

- [ ] You've done well, However, kindly check some key point note I pointed out to meet the requirements before moving to the next project 👍 

- [ ] The second query screenshot is close or rather has little effect. Kindly make reference to the last reviewers' hints given to have a variation to show efficiency in the second query.

### First query:
![image](https://github.com/ybadr99/vet-clinic-database/assets/50990925/8b73cf71-7567-4fe1-a0b4-f4e1e7b4f854)

### Second query:
![image](https://github.com/ybadr99/vet-clinic-database/assets/50990925/c4d217d8-4f97-407a-9a35-253024d8abd0)


_Check the comments for a detailed review 

# Optional suggestions 

Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing really improves your application.

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise.

As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s).

2023-07-20 00:04 UTC, brainconnect93 approved these changes
## Status: Approved :heavy_check_mark:

Hi @ybadr99, 👋 👋  

Your project is complete! Great job for following the project requirement🥇. There is nothing else to say other than... it's time to merge it 🍾🚢 :shipit: . Congratulations!  🎉💯🌟 


<img src="https://user-images.githubusercontent.com/85113567/184604589-430cf4bc-1d2e-4603-976a-7a48a899ea35.gif" width="600px" height="300px">

## Good Points 👍

- Populated database with data ✔️
- Created index on required columns ✔️
- Use of the explain analyze command ✔️

## Optional changes

_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers..Happy coding!..and keep soaring higher! 💻 🍷 🚀 

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me @brainconnect93 in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have 2 more limited reviews per this project. If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-07-20 00:06 UTC, merged